jQuery.event.special.touchstart={setup:function(e,t,o){this.addEventListener("touchstart",o,{passive:!t.includes("noPreventDefault")})}},jQuery.event.special.touchmove={setup:function(e,t,o){this.addEventListener("touchmove",o,{passive:!t.includes("noPreventDefault")})}},jQuery.event.special.wheel={setup:function(e,t,o){this.addEventListener("wheel",o,{passive:!0})}},jQuery.event.special.mousewheel={setup:function(e,t,o){this.addEventListener("mousewheel",o,{passive:!0})}},$((function(){function e(){var e=$(window).height();$("#accueil").css({height:e})}e(),$(window).on("resize",(function(){e()})),$(".owl-carousel").owlCarousel({loop:!0,margin:30,responsiveClass:!0,responsive:{0:{items:2,nav:!0},600:{items:3,nav:!1},1e3:{items:4,nav:!0,loop:!1}}}),$("#charts").waypoint((function(){"use strict";$(".timer1").countTo({from:0,to:125,speed:125,refreshInterval:1}),$(".timer2").countTo({from:0,to:71,speed:250,refreshInterval:1}),$(".timer3").countTo({from:0,to:212,speed:100,refreshInterval:1})}),{offset:500});var t=$(".gallery").imagesLoaded((function(){t.isotope({})}));$("#filters").on("click","button",(function(){var e=$(this).attr("data-filter");t.isotope({filter:e})})),t.isotope({filter:"*"}),$(".gallery-inner").magnificPopup({delegate:" .popup-link",gallery:{enabled:!0,navigateByImgClick:!0,arrowMarkup:'<button title="%title%" type="button" class="mfp-arrow mfp-arrow-%dir%"></button>',tPrev:"Previous (Left arrow key)",tNext:"Next (Right arrow key)"},type:"image",mainClass:"mfp-fade",tLoading:"Loading..."}),$("#filters .btn").tooltip()})),$(window).load((function(){"use strict";$("#status").fadeOut(),$("#preloader").delay(100).fadeOut("slow")}));
/*!
Modal (tuto grafikart) Mentions légales RGPD
*/
let modal=null;const focusableSelector="button, a, input, textarea, select";let focusables=[],previouslyFocusElement=null;const openModal=async e=>{e.preventDefault();const t=e.target.getAttribute("href");modal=t.startsWith("#")?document.querySelector(t):await loadModal(t),focusables=Array.from(modal.querySelectorAll(focusableSelector)),previouslyFocusElement=document.querySelector(":focus"),modal.style.display=null,focusables[0].focus(),modal.removeAttribute("aria-hidden"),modal.setAttribute("aria-modal","true"),modal.querySelector(".js-modal-close").addEventListener("click",closeModal)},closeModal=e=>{null!==modal&&(null!==previouslyFocusElement&&previouslyFocusElement.focus(),e.preventDefault(),window.setTimeout((()=>{modal.style.display="none",modal=null}),500),modal.setAttribute("aria-hidden","true"),modal.removeAttribute("aria-modal"),modal.querySelector(".js-modal-close").removeEventListener("click",closeModal))},focusInModal=e=>{e.preventDefault();let t=focusables.findIndex((e=>e===modal.querySelector(":focus")));!0===e.shiftKey?t--:t++,t>=focusables.length&&(t=0),t<0&&(t=focusables.length-1),focusables[t].focus()},loadModal=async e=>{const t="#"+e.split("#")[1],o=document.querySelector(t);if(null!==o)return o;const s=await fetch(e).then((e=>e.text())),r=document.createRange().createContextualFragment(s).querySelector(t);if(null===r)throw`L'élément ${t} n'a pas été trouvé dans la page ${e}`;return document.body.append(r),r};document.querySelectorAll(".js-modal").forEach((e=>{e.addEventListener("click",openModal)})),window.addEventListener("keydown",(e=>{"Escape"!==e.key&&"Esc"!==e.key||closeModal(e),"Tab"===e.key&&null!==modal&&focusInModal(e)})),$("#projets").waypoint((function(){"use strict";$(".timer1").countTo({from:0,to:125,speed:125,refreshInterval:1}),$(".timer2").countTo({from:0,to:71,speed:250,refreshInterval:1}),$(".timer3").countTo({from:0,to:212,speed:100,refreshInterval:1})}),{offset:500});var Waypoint=new Waypoint({element:document.getElementById("projets"),handler:function(){document.querySelector(".navbar").classList.toggle("navbarVisible")}})
/*!
Pas de # des ancres dans l'url
*/;const removeAnchors=function(e){let t=e.target.getAttribute("href"),o=document.querySelector(t);window.scrollTo(0,o.offsetTop),e.preventDefault()};let links=document.querySelectorAll('a[href^="#accueil"], a[href^="#presentation"], a[href^="#competences"], a[href^="#projets"], a[href^="#contact"], a[href^="#modal"]');links.forEach((function(e){e.addEventListener("click",removeAnchors)}))
/*! Wow-like Effect
https://developer.mozilla.org/fr/docs/Web/API/Intersection_Observer_API#compatibilit%C3%A9_des_navigateurs
*/;const ratio=.1,options={root:null,rootMargin:"0px",threshold:.1},handleIntersect=(e,t)=>{e.forEach((e=>{e.intersectionRatio>.1&&(e.target.classList.remove("reveal"),t.unobserve(e.target))}))};document.documentElement.classList.add("reveal-loaded");const observer=new IntersectionObserver(handleIntersect,options);document.querySelectorAll(".reveal").forEach((e=>{observer.observe(e)})),window.matchMedia("(min-width: 992px)").matches?$.backstretch(["https://picsum.photos/1100/600?random=1","https://picsum.photos/1100/600?random=2","https://picsum.photos/1100/600?random=3","https://picsum.photos/1100/600?random=4","https://picsum.photos/1100/600?random=5","https://picsum.photos/1100/600?random=6"],{duration:4e3,fade:750}):$.backstretch(["https://picsum.photos/375/675?random=1","https://picsum.photos/375/675?random=2","https://picsum.photos/375/675?random=3","https://picsum.photos/375/675?random=4","https://picsum.photos/375/675?random=5"],{duration:4e3,fade:750});